# Generated by Django 4.2.4 on 2023-10-09 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('user_type', models.CharField(choices=[('employee', 'Employee'), ('company', 'Company'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_users', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_position_in_company', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('joined_date', models.DateField()),
                ('address_line2', models.CharField(max_length=255)),
                ('end_date', models.DateField()),
                ('city', models.CharField(max_length=255)),
                ('is_working', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=255)),
                ('is_working_employee', models.BooleanField(default=False)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_unique_id', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('company_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_image', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('is_employee', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('user_unique_id', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('resume_file', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('key_responsibilities', models.TextField()),
                ('experience_required', models.CharField(max_length=255)),
                ('qualification_required', models.CharField(max_length=255)),
                ('key_skills', models.CharField(max_length=255)),
                ('date_posted', models.DateField()),
                ('application_last_date', models.DateField()),
                ('package_details', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('job_category', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('company_website', models.CharField(max_length=255)),
                ('about_company', models.CharField(max_length=255)),
                ('company_verified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('new_applied_category', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExperienceEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_education', models.BooleanField(default=False)),
                ('is_experience', models.BooleanField(default=False)),
                ('experience_education_document', models.FileField(upload_to='experience_documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_job_id', models.IntegerField()),
                ('applied_job_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_department_name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employee_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
