# Generated by Django 4.2.4 on 2023-10-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employeeexperienceeducation_experience_education_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='to_date',
        ),
    ]
