# Generated by Django 4.2.4 on 2023-10-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_employee_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
