# Generated by Django 4.2.4 on 2023-10-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperienceeducation',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation', to_field='organisation_name'),
        ),
    ]
