# Generated by Django 4.2.4 on 2023-10-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_employeeeducation_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='organization_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization', to_field='organization_name'),
        ),
    ]
