# Generated by Django 4.2.4 on 2023-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_organization_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='course_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='job_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
