# Generated by Django 4.2.4 on 2023-10-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_employeeeducation_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='education_document',
            field=models.FileField(null=True, upload_to='ed_documents'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='organization_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', to_field='organization_name'),
        ),
    ]
