# Generated by Django 4.2.4 on 2023-10-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_employeeeducation_education_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_unique_id',
        ),
    ]
