# Generated by Django 4.2.4 on 2023-10-26 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_company_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_employee',
            name='company_id',
        ),
        migrations.AddField(
            model_name='company_employee',
            name='company_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
