# Generated by Django 4.2.4 on 2023-10-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_companysector_company_company_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydepartment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='company_department_name',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.companysector'),
        ),
    ]
