# Generated by Django 4.2.4 on 2023-11-03 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_jobdetail_tag_delete_jobdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='company_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
