# Generated by Django 5.0.3 on 2024-03-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='tags',
        ),
    ]
