# Generated by Django 5.0.3 on 2024-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='employee.skill'),
        ),
    ]
