# Generated by Django 5.0.3 on 2024-03-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
