# Generated by Django 5.0.3 on 2024-03-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_jobdetail_tags'),
        ('employee', '0002_employeeappliedjobs_employeeeducation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='employee.skill'),
        ),
    ]
