# Generated by Django 5.0.3 on 2024-03-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_jobdetail_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='contact_details',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysector',
            name='departments',
            field=models.ManyToManyField(to='company.department'),
        ),
    ]
