# Generated by Django 4.2.4 on 2023-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_user_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_working',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_working_employee',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_position_in_company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_name',
        ),
        migrations.AddField(
            model_name='company',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
