# Generated by Django 4.2.4 on 2023-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperienceeducation',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeexperienceeducation',
            name='course_job_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
