# Generated by Django 4.2.4 on 2023-10-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employeeexperienceeducation_experience_education_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperienceeducation',
            name='experience_education_document',
            field=models.FileField(upload_to='my_picture'),
        ),
    ]
