# Generated by Django 4.2.4 on 2023-10-10 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employee_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_unique_id',
        ),
    ]
