# Generated by Django 4.2.4 on 2023-10-15 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_employeeeducation_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='course_job_name',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='education_document',
            field=models.FileField(upload_to='ed_documents'),
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('experience_document', models.FileField(upload_to='ex_documents')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companylist', to_field='company_name')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
