# Generated by Django 4.2.4 on 2023-10-15 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_company_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
