# Generated by Django 4.2.4 on 2023-10-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_company_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company', to_field='company_name'),
        ),
        migrations.DeleteModel(
            name='CompanyList',
        ),
    ]
