# Generated by Django 4.2.4 on 2023-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_companydepartment_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysector',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
