# Generated by Django 4.2.4 on 2023-11-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_jobdetail_company_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='keywords_tags',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
